import Foundation

struct EsmaItem: Identifiable, Hashable {
    let id: Int
    let name: String
    let arabic: String
    let meaning: String
    let targetCount: Int
    
    // Uygulama geneli statik Esmaül Hüsna listesi
    // Not: Performans ve satır tasarrufu için örnek bir liste verilmiştir.
    static let all: [EsmaItem] = [
        EsmaItem(id: 1, name: "Ya Allah", arabic: "اللَّهُ", meaning: "esma_mean_1", targetCount: 66),
        EsmaItem(id: 2, name: "Ya Rahman", arabic: "الرَّحْمَنُ", meaning: "esma_mean_2", targetCount: 298),
        EsmaItem(id: 3, name: "Ya Rahim", arabic: "الرَّحِيمُ", meaning: "esma_mean_3", targetCount: 258),
        EsmaItem(id: 4, name: "Ya Melik", arabic: "الْمَلِكُ", meaning: "esma_mean_4", targetCount: 90),
        EsmaItem(id: 5, name: "Ya Kuddüs", arabic: "الْقُدُّوسُ", meaning: "esma_mean_5", targetCount: 170),
        EsmaItem(id: 6, name: "Ya Selam", arabic: "السَّلَامُ", meaning: "esma_mean_6", targetCount: 131),
        EsmaItem(id: 7, name: "Ya Mü'min", arabic: "الْمُؤْمِنُ", meaning: "esma_mean_7", targetCount: 136),
        EsmaItem(id: 8, name: "Ya Müheymin", arabic: "الْمُهَيْمِنُ", meaning: "esma_mean_8", targetCount: 145),
        EsmaItem(id: 9, name: "Ya Aziz", arabic: "الْعَزِيزُ", meaning: "esma_mean_9", targetCount: 94),
        EsmaItem(id: 10, name: "Ya Cebbar", arabic: "الْجَبَّارُ", meaning: "esma_mean_10", targetCount: 206),
        EsmaItem(id: 11, name: "Ya Mütekebbir", arabic: "الْمُتَكَبِّرُ", meaning: "esma_mean_11", targetCount: 662),
        EsmaItem(id: 12, name: "Ya Halik", arabic: "الْخَالِقُ", meaning: "esma_mean_12", targetCount: 731),
        EsmaItem(id: 13, name: "Ya Bari", arabic: "الْبَارِئُ", meaning: "esma_mean_13", targetCount: 214),
        EsmaItem(id: 14, name: "Ya Musavvir", arabic: "الْمُصَوِّرُ", meaning: "esma_mean_14", targetCount: 336),
        EsmaItem(id: 15, name: "Ya Gaffar", arabic: "الْغَفَّارُ", meaning: "esma_mean_15", targetCount: 1281),
        EsmaItem(id: 16, name: "Ya Kahhar", arabic: "الْقَهَّارُ", meaning: "esma_mean_16", targetCount: 306),
        EsmaItem(id: 17, name: "Ya Vehhab", arabic: "الْوَهَّابُ", meaning: "esma_mean_17", targetCount: 196),
        EsmaItem(id: 18, name: "Ya Rezzak", arabic: "الرَّزَّاقُ", meaning: "esma_mean_18", targetCount: 308),
        EsmaItem(id: 19, name: "Ya Fettah", arabic: "الْفَتَّاحُ", meaning: "esma_mean_19", targetCount: 489),
        EsmaItem(id: 20, name: "Ya Alim", arabic: "الْعَلِيمُ", meaning: "esma_mean_20", targetCount: 150),
        EsmaItem(id: 21, name: "Ya Kabid", arabic: "الْقَابِضُ", meaning: "esma_mean_21", targetCount: 903),
        EsmaItem(id: 22, name: "Ya Basit", arabic: "الْبَاسِطُ", meaning: "esma_mean_22", targetCount: 72),
        EsmaItem(id: 23, name: "Ya Hafid", arabic: "الْخَافِضُ", meaning: "esma_mean_23", targetCount: 1481),
        EsmaItem(id: 24, name: "Ya Rafi", arabic: "الرَّافِعُ", meaning: "esma_mean_24", targetCount: 351),
        EsmaItem(id: 25, name: "Ya Muizz", arabic: "الْمُعِزُّ", meaning: "esma_mean_25", targetCount: 117),
        EsmaItem(id: 26, name: "Ya Muzill", arabic: "الْمُذِلُّ", meaning: "esma_mean_26", targetCount: 770),
        EsmaItem(id: 27, name: "Ya Semi", arabic: "السَّمِيعُ", meaning: "esma_mean_27", targetCount: 180),
        EsmaItem(id: 28, name: "Ya Basir", arabic: "الْبَصِيرُ", meaning: "esma_mean_28", targetCount: 302),
        EsmaItem(id: 29, name: "Ya Hakem", arabic: "الْحَكَمُ", meaning: "esma_mean_29", targetCount: 68),
        EsmaItem(id: 30, name: "Ya Adl", arabic: "الْعَدْلُ", meaning: "esma_mean_30", targetCount: 104),
        EsmaItem(id: 31, name: "Ya Latif", arabic: "اللَّطِيفُ", meaning: "esma_mean_31", targetCount: 129),
        EsmaItem(id: 32, name: "Ya Habir", arabic: "الْخَبِيرُ", meaning: "esma_mean_32", targetCount: 812),
        EsmaItem(id: 33, name: "Ya Halim", arabic: "الْحَلِيمُ", meaning: "esma_mean_33", targetCount: 88),
        EsmaItem(id: 34, name: "Ya Azim", arabic: "الْعَظِيمُ", meaning: "esma_mean_34", targetCount: 1020),
        EsmaItem(id: 35, name: "Ya Gafur", arabic: "الْغَفُورُ", meaning: "esma_mean_35", targetCount: 1286),
        EsmaItem(id: 36, name: "Ya Şekur", arabic: "الشَّكُورُ", meaning: "esma_mean_36", targetCount: 526),
        EsmaItem(id: 37, name: "Ya Aliyy", arabic: "الْعَلِيُّ", meaning: "esma_mean_37", targetCount: 110),
        EsmaItem(id: 38, name: "Ya Kebir", arabic: "الْكَبِيرُ", meaning: "esma_mean_38", targetCount: 232),
        EsmaItem(id: 39, name: "Ya Hafiz", arabic: "الْحَفِيظُ", meaning: "esma_mean_39", targetCount: 998),
        EsmaItem(id: 40, name: "Ya Mukit", arabic: "الْمُقِيتُ", meaning: "esma_mean_40", targetCount: 550),
        EsmaItem(id: 41, name: "Ya Hasib", arabic: "الْحَسِيبُ", meaning: "esma_mean_41", targetCount: 80),
        EsmaItem(id: 42, name: "Ya Celil", arabic: "الْجَلِيلُ", meaning: "esma_mean_42", targetCount: 73),
        EsmaItem(id: 43, name: "Ya Kerim", arabic: "الْكَرِيمُ", meaning: "esma_mean_43", targetCount: 270),
        EsmaItem(id: 44, name: "Ya Rakib", arabic: "الرَّقِيبُ", meaning: "esma_mean_44", targetCount: 312),
        EsmaItem(id: 45, name: "Ya Mücib", arabic: "الْمُجِيبُ", meaning: "esma_mean_45", targetCount: 55),
        EsmaItem(id: 46, name: "Ya Vasi", arabic: "الْوَاسِعُ", meaning: "esma_mean_46", targetCount: 137),
        EsmaItem(id: 47, name: "Ya Hakim", arabic: "الْحَكِيمُ", meaning: "esma_mean_47", targetCount: 78),
        EsmaItem(id: 48, name: "Ya Vedud", arabic: "الْوَدُودُ", meaning: "esma_mean_48", targetCount: 20),
        EsmaItem(id: 49, name: "Ya Mecid", arabic: "الْمَجِيدُ", meaning: "esma_mean_49", targetCount: 57),
        EsmaItem(id: 50, name: "Ya Bais", arabic: "الْبَاعِثُ", meaning: "esma_mean_50", targetCount: 573),
        EsmaItem(id: 51, name: "Ya Şehid", arabic: "الشَّهِيدُ", meaning: "esma_mean_51", targetCount: 319),
        EsmaItem(id: 52, name: "Ya Hak", arabic: "الْحَقُّ", meaning: "esma_mean_52", targetCount: 108),
        EsmaItem(id: 53, name: "Ya Vekil", arabic: "الْوَكِيلُ", meaning: "esma_mean_53", targetCount: 66),
        EsmaItem(id: 54, name: "Ya Kaviyy", arabic: "الْقَوِيُّ", meaning: "esma_mean_54", targetCount: 116),
        EsmaItem(id: 55, name: "Ya Metin", arabic: "الْمَتِينُ", meaning: "esma_mean_55", targetCount: 500),
        EsmaItem(id: 56, name: "Ya Veliyy", arabic: "الْوَلِيُّ", meaning: "esma_mean_56", targetCount: 46),
        EsmaItem(id: 57, name: "Ya Hamid", arabic: "الْحَمِيدُ", meaning: "esma_mean_57", targetCount: 62),
        EsmaItem(id: 58, name: "Ya Muhsi", arabic: "الْمُحْصِي", meaning: "esma_mean_58", targetCount: 148),
        EsmaItem(id: 59, name: "Ya Mübdî", arabic: "الْمُبْدِئُ", meaning: "esma_mean_59", targetCount: 56),
        EsmaItem(id: 60, name: "Ya Muîd", arabic: "الْمُعِيدُ", meaning: "esma_mean_60", targetCount: 124),
        EsmaItem(id: 61, name: "Ya Muhyi", arabic: "الْمُحْيِي", meaning: "esma_mean_61", targetCount: 68),
        EsmaItem(id: 62, name: "Ya Mümît", arabic: "اَلْمُمِيتُ", meaning: "esma_mean_62", targetCount: 490),
        EsmaItem(id: 63, name: "Ya Hayy", arabic: "الْحَيُّ", meaning: "esma_mean_63", targetCount: 18),
        EsmaItem(id: 64, name: "Ya Kayyum", arabic: "الْقَيُّومُ", meaning: "esma_mean_64", targetCount: 156),
        EsmaItem(id: 65, name: "Ya Vacid", arabic: "الْوَاجِدُ", meaning: "esma_mean_65", targetCount: 14),
        EsmaItem(id: 66, name: "Ya Macid", arabic: "الْمَاجِدُ", meaning: "esma_mean_66", targetCount: 48),
        EsmaItem(id: 67, name: "Ya Vahid", arabic: "الْوَاحِدُ", meaning: "esma_mean_67", targetCount: 19),
        EsmaItem(id: 68, name: "Ya Samed", arabic: "الصَّمَدُ", meaning: "esma_mean_68", targetCount: 134),
        EsmaItem(id: 69, name: "Ya Kadir", arabic: "الْقَادِرُ", meaning: "esma_mean_69", targetCount: 305),
        EsmaItem(id: 70, name: "Ya Muktedir", arabic: "الْمُقْتَدِرُ", meaning: "esma_mean_70", targetCount: 744),
        EsmaItem(id: 71, name: "Ya Mukaddim", arabic: "الْمُقَدِّمُ", meaning: "esma_mean_71", targetCount: 184),
        EsmaItem(id: 72, name: "Ya Muahhir", arabic: "الْمُؤَخِّرُ", meaning: "esma_mean_72", targetCount: 847),
        EsmaItem(id: 73, name: "Ya Evvel", arabic: "الأوَّلُ", meaning: "esma_mean_73", targetCount: 37),
        EsmaItem(id: 74, name: "Ya Ahir", arabic: "الآخِرُ", meaning: "esma_mean_74", targetCount: 801),
        EsmaItem(id: 75, name: "Ya Zahir", arabic: "الظَّاهِرُ", meaning: "esma_mean_75", targetCount: 1106),
        EsmaItem(id: 76, name: "Ya Batın", arabic: "الْبَاطِنُ", meaning: "esma_mean_76", targetCount: 62),
        EsmaItem(id: 77, name: "Ya Vali", arabic: "الْوَالِي", meaning: "esma_mean_77", targetCount: 47),
        EsmaItem(id: 78, name: "Ya Müteali", arabic: "الْمُتَعَالِي", meaning: "esma_mean_78", targetCount: 551),
        EsmaItem(id: 79, name: "Ya Berr", arabic: "الْبَرُّ", meaning: "esma_mean_79", targetCount: 202),
        EsmaItem(id: 80, name: "Ya Tevvab", arabic: "التَّوَّابُ", meaning: "esma_mean_80", targetCount: 409),
        EsmaItem(id: 81, name: "Ya Müntekim", arabic: "الْمُنْتَقِمُ", meaning: "esma_mean_81", targetCount: 630),
        EsmaItem(id: 82, name: "Ya Afuvv", arabic: "العَفُوُّ", meaning: "esma_mean_82", targetCount: 156),
        EsmaItem(id: 83, name: "Ya Raûf", arabic: "الرَّؤُوفُ", meaning: "esma_mean_83", targetCount: 287),
        EsmaItem(id: 84, name: "Ya Malikül Mülk", arabic: "مَالِكُ الْمُلْكِ", meaning: "esma_mean_84", targetCount: 212),
        EsmaItem(id: 85, name: "Ya Zül Celali vel İkram", arabic: "ذُو الْجَلالِ وَالإكْرَامِ", meaning: "esma_mean_85", targetCount: 1100),
        EsmaItem(id: 86, name: "Ya Muksit", arabic: "الْمُقْسِطُ", meaning: "esma_mean_86", targetCount: 209),
        EsmaItem(id: 87, name: "Ya Cami", arabic: "الْجَامِعُ", meaning: "esma_mean_87", targetCount: 114),
        EsmaItem(id: 88, name: "Ya Gani", arabic: "الْغَنِيُّ", meaning: "esma_mean_88", targetCount: 1060),
        EsmaItem(id: 89, name: "Ya Muğni", arabic: "الْمُغْنِي", meaning: "esma_mean_89", targetCount: 1100),
        EsmaItem(id: 90, name: "Ya Mani", arabic: "الْمَانِعُ", meaning: "esma_mean_90", targetCount: 161),
        EsmaItem(id: 91, name: "Ya Darr", arabic: "الضَّارُ", meaning: "esma_mean_91", targetCount: 1001),
        EsmaItem(id: 92, name: "Ya Nafi", arabic: "النَّافِعُ", meaning: "esma_mean_92", targetCount: 201),
        EsmaItem(id: 93, name: "Ya Nur", arabic: "النُّورُ", meaning: "esma_mean_93", targetCount: 256),
        EsmaItem(id: 94, name: "Ya Hadi", arabic: "الْهَادِي", meaning: "esma_mean_94", targetCount: 20),
        EsmaItem(id: 95, name: "Ya Bedi", arabic: "الْبَدِيعُ", meaning: "esma_mean_95", targetCount: 86),
        EsmaItem(id: 96, name: "Ya Baki", arabic: "الْبَاقِي", meaning: "esma_mean_96", targetCount: 113),
        EsmaItem(id: 97, name: "Ya Varis", arabic: "الْوَارِثُ", meaning: "esma_mean_97", targetCount: 707),
        EsmaItem(id: 98, name: "Ya Reşid", arabic: "الرَّشِيدُ", meaning: "esma_mean_98", targetCount: 514),
        EsmaItem(id: 99, name: "Ya Sabur", arabic: "الصَّبُورُ", meaning: "esma_mean_99", targetCount: 298)
    ]
}